### ISSUE TITLE
Negative lives in Chrome

### ISSUE THREAD

**Issue by rillig** [osnr/horrifying-pdf-experiments#3]
> ![image](https://user-images.githubusercontent.com/3233724/67978157-c5894380-fc19-11e9-886b-355943cfab7f.png)

When I reload the PDF, it starts at 0 points and 3 lives.

After I clear the 20 bricks for the first time, I get a congratulations message, as expected. Then, 20 new bricks are placed, and I can play the next round.

When I have cleared the next 20 bricks, no message appears, my score is at 40 and I cannot get any more points.

Therefore I let the ball drop, and when my lives decrease to 0, I get a game over message. After that, the game continues, and my lives continue to decrease into negative numbers, which is unexpected.

I think it should be possible to either reset the score to 0 after each win, or alternatively check for `score % 20 === 0` instead of `score === 20` (just a guess at how the code looks like).

**Comment by osnr** [comment]
fixed in https://github.com/osnr/horrifying-pdf-experiments/commit/f8cd186b687abc32595670c5ce7acb3f491efbcd right?
